"""Wave10 CuTe integration contract for the Mamba3 12-tile vector copy path.

Wave9 proved the representative ``uint4`` copy probe is correct and faster than
the scalar reference on GB10.  Wave10 turns that evidence into an integration
artifact for the CuTe lane: explicit guards, expected layouts, an API sketch,
failure modes, and a retained decision receipt.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib
import json
import pathlib
import sys
from typing import Any


ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path = [entry for entry in sys.path if entry != str(ROOT)]
sys.path.insert(0, str(ROOT))

wave6 = importlib.import_module("tools.probes.mamba3_wgmma_wave6_copy_path")
wave8 = importlib.import_module("tools.probes.mamba3_wgmma_wave8_copy_evidence")
wave9 = importlib.import_module("tools.probes.mamba3_wgmma_wave9_copy_probe")


DATE = "2026-04-30"
RECEIPT_NAME = "mamba3_mono_wgmma_copy_path_wave10_cute_integration_2026_04_30"
RECEIPT_PATH = (
    "docs/status/mamba3_mono_wgmma_copy_path_wave10_receipt_2026_04_30.json"
)
GUIDE_PATH = (
    "docs/status/mamba3_mono_wgmma_copy_path_wave10_cute_integration_2026_04_30.md"
)
GUARD_HEADER_PATH = "tools/probes/mamba3_wgmma_wave10_copy_guards.hpp"
SCHEMA = "mamba3_wave10_cute_vector_copy_integration_v1"
CONTRACT_SCHEMA = "mamba3_wave10_cute_vector_copy_guard_contract_v1"
HEADER_SCHEMA_COMMENT = "mamba3_wave10_copy_guard_header_v1"


def _canonical(data: dict[str, Any]) -> str:
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


def _read_json(path: pathlib.Path) -> dict[str, Any]:
    return json.loads(path.read_text())


def _write_text(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def _write_json(path: pathlib.Path, data: dict[str, Any]) -> None:
    _write_text(path, _canonical(data))


def render_guard_header() -> str:
    return """// Generated by tools/probes/mamba3_wgmma_wave10_copy_integration.py.
// schema: mamba3_wave10_copy_guard_header_v1
#pragma once

#include <stdint.h>

namespace mamba3_wave10_copy {

constexpr int kTileRows = 64;
constexpr int kTileCols = 64;
constexpr int kBf16Bytes = 2;
constexpr int kVectorBytes = 16;
constexpr int kWarpThreads = 32;
constexpr int kLogicalTileCount = 12;
constexpr int kGlobalTileCount = 10;
constexpr int kLocalStageTileCount = 2;
constexpr int kTileElements = kTileRows * kTileCols;
constexpr int kRowBytes = kTileCols * kBf16Bytes;
constexpr int kTileBytes = kTileElements * kBf16Bytes;
constexpr int kVectorsPerRow = kRowBytes / kVectorBytes;
constexpr int kVectorsPerTile = kTileBytes / kVectorBytes;
constexpr int kElementsPerVector = kVectorBytes / kBf16Bytes;
constexpr int kTotalVectors = kLogicalTileCount * kVectorsPerTile;
constexpr int kTotalElements = kLogicalTileCount * kTileElements;
constexpr int kDynamicSmemBytes = kLogicalTileCount * kTileBytes;

constexpr bool kStaticLayoutGuardsPass =
    kTileRows == 64 &&
    kTileCols == 64 &&
    kBf16Bytes == 2 &&
    kVectorBytes == 16 &&
    kRowBytes == 128 &&
    kTileBytes == 8192 &&
    kVectorsPerRow == 8 &&
    kVectorsPerTile == 512 &&
    kElementsPerVector == 8 &&
    kTotalVectors == 6144 &&
    kDynamicSmemBytes == 98304 &&
    (kRowBytes % kVectorBytes) == 0 &&
    (kTileBytes % kVectorBytes) == 0 &&
    kGlobalTileCount + kLocalStageTileCount == kLogicalTileCount;

enum GuardStatusBits : int {
  kGuardStatusOk = 0,
  kGuardMisalignedGlobalSource = 1 << 0,
  kGuardMisalignedLocalStageSource = 1 << 1,
  kGuardMisalignedDestination = 1 << 2,
  kGuardMisalignedSmem = 1 << 3,
  kGuardInvalidBlockThreads = 1 << 4,
};

__host__ __device__ __forceinline__ bool is_aligned_16(const void* ptr) {
  return (reinterpret_cast<uintptr_t>(ptr) & (kVectorBytes - 1)) == 0;
}

__host__ __device__ __forceinline__ bool row_stride_guard(int64_t row_stride_bytes) {
  return row_stride_bytes == kRowBytes &&
      (row_stride_bytes % kVectorBytes) == 0;
}

__host__ __device__ __forceinline__ bool panel_offset_guard(int64_t panel_offset_bytes) {
  return (panel_offset_bytes % kVectorBytes) == 0;
}

__host__ __device__ __forceinline__ bool dynamic_smem_optin_guard(
    int max_dynamic_smem_optin_bytes) {
  return max_dynamic_smem_optin_bytes >= kDynamicSmemBytes;
}

__device__ __forceinline__ int runtime_guard_bits(
    const void* global_src,
    const void* local_stage_src,
    const void* dst,
    const void* smem,
    int block_threads) {
  int bits = kGuardStatusOk;
  if (!is_aligned_16(global_src)) {
    bits |= kGuardMisalignedGlobalSource;
  }
  if (!is_aligned_16(local_stage_src)) {
    bits |= kGuardMisalignedLocalStageSource;
  }
  if (!is_aligned_16(dst)) {
    bits |= kGuardMisalignedDestination;
  }
  if (!is_aligned_16(smem)) {
    bits |= kGuardMisalignedSmem;
  }
  if (block_threads <= 0 || (block_threads % kWarpThreads) != 0) {
    bits |= kGuardInvalidBlockThreads;
  }
  return bits;
}

}  // namespace mamba3_wave10_copy
"""


def _guard_header_sha256() -> str:
    return hashlib.sha256(render_guard_header().encode()).hexdigest()


def _tile_layouts(alignment_evidence: dict[str, Any]) -> list[dict[str, Any]]:
    layouts: list[dict[str, Any]] = []
    for tile in alignment_evidence.get("tile_evidence", []):
        if not isinstance(tile, dict):
            continue
        layouts.append(
            {
                "name": tile.get("name"),
                "source_space": tile.get("source_space"),
                "destination_space": tile.get("destination_space"),
                "source_expr": tile.get("source_expr"),
                "destination_expr": tile.get("destination_expr"),
                "layout_kind": tile.get("layout_kind"),
                "row_bytes": tile.get("row_bytes"),
                "row_stride_alignment_bytes": tile.get("row_stride_alignment_bytes"),
                "panel_offset_alignment_bytes": tile.get("panel_offset_alignment_bytes"),
                "vector_type": tile.get("vector_type"),
                "vector_bytes": tile.get("vector_bytes"),
                "vectors_per_tile": tile.get("vectors_per_tile"),
                "tma_candidate": tile.get("tma_candidate"),
                "transpose_layout_proof": tile.get("transpose_layout_proof"),
            }
        )
    return layouts


def _guard_conditions() -> dict[str, list[str]]:
    return {
        "compile_time": [
            "tile shape is 64x64 bf16",
            "row_bytes == 128 and tile_bytes == 8192",
            "vector copy lane is 16 bytes, eight contiguous bf16 values",
            "row_bytes and tile_bytes have zero vector tail",
            "logical tile split is 10 global-source tiles plus 2 CTA-local-stage tiles",
            "dynamic SMEM contract is 98304 bytes for the 12-tile staging buffer",
        ],
        "runtime": [
            "global source base pointer is 16-byte aligned",
            "CTA-local stage source base pointer is 16-byte aligned",
            "destination/staging pointer is 16-byte aligned",
            "dynamic SMEM base pointer is 16-byte aligned",
            "emitted row stride remains 128 bytes and a multiple of 16",
            "panel offsets remain multiples of 16 bytes",
            "block_threads is a positive warp multiple",
            "device opt-in dynamic SMEM capacity is at least 98304 bytes",
        ],
        "layout": [
            "K, Q, state, dPhiO, PsiV, and dstates panels use 128-byte physical rows",
            "K_T and Q_T are CuTe/GMMA physical-layout or view operands",
            "K_T and Q_T are not per-column 2-byte BF16 scatters",
            "no masked tail or scalar cleanup path is emitted for these 64x64 tiles",
        ],
        "resource": [
            "ptxas registers/thread stays at or below the Wave6 narrow-vector budget",
            "ptxas spill stores and loads are zero",
            "total reported SMEM stays within the narrow-vector budget",
        ],
        "synchronization": [
            "__syncthreads() after the 12-tile SMEM load before WGMMA consumption",
            "__syncthreads() after the destination write before reusing the staging buffer",
        ],
    }


def _api_sketch() -> dict[str, Any]:
    return {
        "guard_header": GUARD_HEADER_PATH,
        "status_word": "int bitmask using mamba3_wave10_copy::GuardStatusBits",
        "device_guard": (
            "mamba3_wave10_copy::runtime_guard_bits(global_src, local_stage_src, "
            "dst, smem, block_threads)"
        ),
        "copy_helper_signature": (
            "template <class GlobalTiles, class LocalStageTiles, class SmemTiles> "
            "CUTE_DEVICE void copy_12tile_uint4_to_smem(GlobalTiles const& global_tiles, "
            "LocalStageTiles const& local_stage_tiles, SmemTiles& smem_tiles, int chunk_idx, "
            "int* status)"
        ),
        "sequence": [
            "run static layout assertions and runtime guard bit checks",
            "copy ten global 64x64 bf16 tiles as uint4 lanes into SMEM",
            "copy two CTA-local dstates 64x64 bf16 panels as uint4 lanes into SMEM",
            "__syncthreads() before WGMMA reads the staging buffer",
            "run the CuTe/WGMMA math using the physical layouts described in the receipt",
            "__syncthreads() before the next chunk reuses the 12-tile SMEM buffer",
        ],
    }


def _failure_modes() -> list[dict[str, str]]:
    return [
        {
            "mode": "misaligned_source_or_destination",
            "detected_by": "runtime_guard_bits status word",
            "required_action": "do not launch the vector path for that generated layout; use scalar repair or TMA fallback",
        },
        {
            "mode": "row_or_panel_stride_not_16b_aligned",
            "detected_by": "row_stride_guard and panel_offset_guard in generated CuTe code",
            "required_action": "fix the layout mapping before enabling uint4 lanes",
        },
        {
            "mode": "kt_qt_scalar_scatter",
            "detected_by": "Wave8 transpose_layout_proof and generated-code inspection",
            "required_action": "keep K_T/Q_T as physical-layout/view operands or fall back to TMA descriptor smoke",
        },
        {
            "mode": "masked_tail_or_scalar_cleanup_emitted",
            "detected_by": "guard contract and codegen review; no 64x64 bf16 tile has a tail",
            "required_action": "remove the tail path from this specialization before integration",
        },
        {
            "mode": "smem_optin_too_small",
            "detected_by": "dynamic_smem_optin_guard",
            "required_action": "skip vector path on that target; do not use H200-only capacity assumptions",
        },
        {
            "mode": "resource_regression",
            "detected_by": "ptxas metadata and focused compile test",
            "required_action": "keep TMA fallback active if registers exceed budget or any spill appears",
        },
        {
            "mode": "runtime_correctness_regression",
            "detected_by": "byte equality against scalar CUDA reference",
            "required_action": "block integration and switch the next lane run to TMA fallback investigation",
        },
    ]


def build_guard_contract(
    alignment_evidence: dict[str, Any] | None = None,
) -> dict[str, Any]:
    effective_alignment = alignment_evidence or wave8.build_alignment_layout_evidence()
    layouts = _tile_layouts(effective_alignment)
    global_tiles = [tile for tile in layouts if tile.get("source_space") == "global"]
    local_tiles = [tile for tile in layouts if tile.get("source_space") != "global"]

    return {
        "schema": CONTRACT_SCHEMA,
        "date": DATE,
        "guard_header": {
            "path": GUARD_HEADER_PATH,
            "schema_comment": HEADER_SCHEMA_COMMENT,
            "generated_by": "tools/probes/mamba3_wgmma_wave10_copy_integration.py",
            "sha256": _guard_header_sha256(),
            "consumed_by": "tools/probes/mamba3_wgmma_wave9_copy_probe.cu",
        },
        "constants": {
            "logical_tile_count": 12,
            "global_tile_count": 10,
            "local_stage_tile_count": 2,
            "tile_rows": wave6.TILE_ROWS,
            "tile_cols": wave6.TILE_COLS,
            "dtype": "bf16",
            "dtype_bytes": wave6.BF16_BYTES,
            "row_bytes": wave6.ROW_BYTES,
            "tile_bytes": wave6.TILE_BYTES,
            "vector_type": "uint4",
            "vector_bytes": wave6.VECTOR_BYTES,
            "vectors_per_row": wave6.ROW_BYTES // wave6.VECTOR_BYTES,
            "vectors_per_tile": wave6.TILE_BYTES // wave6.VECTOR_BYTES,
            "vectors_per_chunk": 12 * (wave6.TILE_BYTES // wave6.VECTOR_BYTES),
            "dynamic_smem_bytes": 12 * wave6.TILE_BYTES,
        },
        "guard_conditions": _guard_conditions(),
        "expected_data_layouts": {
            "global_source_tiles_per_chunk": len(global_tiles),
            "local_stage_tiles_per_chunk": len(local_tiles),
            "destination": (
                "12 contiguous 64x64 bf16 physical SMEM tiles, each with 128-byte rows "
                "and 512 uint4 lanes"
            ),
            "tiles": layouts,
        },
        "api_sketch": _api_sketch(),
        "failure_modes": _failure_modes(),
    }


def evaluate_guard_contract(contract: dict[str, Any] | None) -> dict[str, Any]:
    if contract is None:
        return {
            "status": "missing_guard_contract",
            "pass": False,
            "failures": ["guard contract must be generated"],
        }

    failures: list[str] = []
    if contract.get("schema") != CONTRACT_SCHEMA:
        failures.append(f"schema must be {CONTRACT_SCHEMA}, got {contract.get('schema')}")

    constants = contract.get("constants")
    if not isinstance(constants, dict):
        failures.append("constants must be present")
        constants = {}
    expected_constants = {
        "logical_tile_count": 12,
        "global_tile_count": 10,
        "local_stage_tile_count": 2,
        "tile_rows": 64,
        "tile_cols": 64,
        "dtype_bytes": 2,
        "row_bytes": 128,
        "tile_bytes": 8192,
        "vector_bytes": 16,
        "vectors_per_row": 8,
        "vectors_per_tile": 512,
        "vectors_per_chunk": 6144,
        "dynamic_smem_bytes": 98304,
    }
    for field, expected in expected_constants.items():
        if constants.get(field) != expected:
            failures.append(f"constants.{field} must be {expected}, got {constants.get(field)}")
    if constants.get("dtype") != "bf16":
        failures.append(f"constants.dtype must be bf16, got {constants.get('dtype')}")
    if constants.get("vector_type") != "uint4":
        failures.append(f"constants.vector_type must be uint4, got {constants.get('vector_type')}")

    layouts = contract.get("expected_data_layouts")
    if not isinstance(layouts, dict):
        failures.append("expected_data_layouts must be present")
        layouts = {}
    tiles = layouts.get("tiles")
    if not isinstance(tiles, list):
        failures.append("expected_data_layouts.tiles must be a list")
        tiles = []
    tile_names = {tile.get("name") for tile in tiles if isinstance(tile, dict)}
    if tile_names != set(wave8.EXPECTED_TILE_NAMES):
        failures.append(f"tiles must cover Wave8 names, got {sorted(tile_names)}")
    if layouts.get("global_source_tiles_per_chunk") != 10:
        failures.append("global_source_tiles_per_chunk must be 10")
    if layouts.get("local_stage_tiles_per_chunk") != 2:
        failures.append("local_stage_tiles_per_chunk must be 2")

    by_name = {tile.get("name"): tile for tile in tiles if isinstance(tile, dict)}
    for transpose_name in ("K_T", "Q_T"):
        proof = by_name.get(transpose_name, {}).get("transpose_layout_proof")
        if not isinstance(proof, dict):
            failures.append(f"{transpose_name}: transpose_layout_proof must be present")
            continue
        if proof.get("vector_compatible") is not True:
            failures.append(f"{transpose_name}: transpose layout must be vector compatible")
        if proof.get("per_column_scalar_scatter") is not False:
            failures.append(f"{transpose_name}: per_column_scalar_scatter must be false")

    guard_conditions = contract.get("guard_conditions")
    if not isinstance(guard_conditions, dict):
        failures.append("guard_conditions must be present")
        guard_conditions = {}
    for section in ("compile_time", "runtime", "layout", "resource", "synchronization"):
        values = guard_conditions.get(section)
        if not isinstance(values, list) or not values:
            failures.append(f"guard_conditions.{section} must be a non-empty list")

    header = contract.get("guard_header")
    if not isinstance(header, dict):
        failures.append("guard_header must be present")
    elif header.get("sha256") != _guard_header_sha256():
        failures.append("guard_header.sha256 must match rendered header")

    api = contract.get("api_sketch")
    if not isinstance(api, dict):
        failures.append("api_sketch must be present")
    elif "runtime_guard_bits" not in api.get("device_guard", ""):
        failures.append("api_sketch.device_guard must name runtime_guard_bits")

    failure_modes = contract.get("failure_modes")
    if not isinstance(failure_modes, list) or len(failure_modes) < 6:
        failures.append("failure_modes must enumerate integration blockers")

    return {
        "status": "pass" if not failures else "fail",
        "pass": not failures,
        "failures": failures,
    }


def _source_evidence(
    runtime_result: dict[str, Any],
    ptxas_ingest: dict[str, Any],
) -> dict[str, Any]:
    return {
        "wave9_runtime_result": wave9.RUNTIME_RESULT_PATH,
        "wave9_ptxas_ingest": wave9.PTXAS_INGEST_PATH,
        "runtime": {
            "device": runtime_result.get("device"),
            "launch": runtime_result.get("launch"),
            "correctness": runtime_result.get("correctness"),
            "timing": runtime_result.get("timing"),
        },
        "ptxas": {
            "kernel_name": ptxas_ingest.get("kernel_name"),
            "metadata": ptxas_ingest.get("metadata"),
        },
    }


def _receipt_blockers(
    *,
    alignment_check: dict[str, Any],
    ptxas_ingest: dict[str, Any],
    ptxas_resource_check: dict[str, Any],
    runtime_check: dict[str, Any],
    guard_contract_check: dict[str, Any],
) -> list[str]:
    blockers: list[str] = []
    if not alignment_check["pass"]:
        blockers.extend(f"alignment/layout: {failure}" for failure in alignment_check["failures"])
    if ptxas_ingest.get("status") != "parsed":
        blockers.extend(f"ptxas-ingest: {failure}" for failure in ptxas_ingest.get("failures", []))
    if ptxas_ingest.get("kernel_name") != wave9.PROBE_KERNEL:
        blockers.append(
            f"ptxas-ingest: kernel_name must be {wave9.PROBE_KERNEL}, got {ptxas_ingest.get('kernel_name')}"
        )
    if not ptxas_resource_check["pass"]:
        blockers.extend(f"ptxas-resource: {failure}" for failure in ptxas_resource_check["failures"])
    if not runtime_check["pass"]:
        blockers.extend(f"runtime: {failure}" for failure in runtime_check["failures"])
    if not guard_contract_check["pass"]:
        blockers.extend(f"guard-contract: {failure}" for failure in guard_contract_check["failures"])
    return blockers


def build_receipt(
    *,
    runtime_result: dict[str, Any] | None = None,
    ptxas_ingest: dict[str, Any] | None = None,
    alignment_evidence: dict[str, Any] | None = None,
) -> dict[str, Any]:
    effective_alignment = alignment_evidence or wave8.build_alignment_layout_evidence()
    effective_runtime = runtime_result or wave9._runtime_missing("attach Wave9 runtime probe JSON")
    effective_ptxas = wave9.normalize_ptxas_ingest(ptxas_ingest)

    alignment_check = wave8.evaluate_alignment_layout_evidence(effective_alignment)
    runtime_check = wave9.evaluate_runtime_result(effective_runtime)
    ptxas_resource_check = wave6.evaluate_ptxas_metadata(
        effective_ptxas.get("metadata"),
        variant="narrow_vector_128b_safe_attempt",
    )
    guard_contract = build_guard_contract(effective_alignment)
    guard_contract_check = evaluate_guard_contract(guard_contract)

    can_integrate = bool(
        alignment_check["pass"]
        and effective_ptxas.get("status") == "parsed"
        and effective_ptxas.get("kernel_name") == wave9.PROBE_KERNEL
        and ptxas_resource_check["pass"]
        and runtime_check["pass"]
        and guard_contract_check["pass"]
    )
    blockers = _receipt_blockers(
        alignment_check=alignment_check,
        ptxas_ingest=effective_ptxas,
        ptxas_resource_check=ptxas_resource_check,
        runtime_check=runtime_check,
        guard_contract_check=guard_contract_check,
    )

    receipt = {
        "receipt": RECEIPT_NAME,
        "schema": SCHEMA,
        "status": (
            "pass_cute_integration_ready_vector_first"
            if can_integrate
            else "fail_cute_integration_blocked"
        ),
        "date": DATE,
        "branch": "worker/mamba3-mono-triton-model",
        "source_receipts": [
            "docs/status/mamba3_mono_wgmma_copy_path_wave8_receipt_2026_04_30.json",
            wave9.RECEIPT_PATH,
        ],
        "decision": {
            "vector_path_ready": can_integrate,
            "recommendation": (
                "integrate_vector_path_next"
                if can_integrate
                else "do_not_integrate_vector_path_until_blockers_clear"
            ),
            "tma_fallback": (
                "fallback_only_if_integrated_cute_lane_regresses_correctness_resources_or_timing"
                if can_integrate
                else "use_tma_descriptor_smoke_if_vector_blockers_are_structural"
            ),
            "summary": (
                "Integrate the 12-tile uint4 vector copy into the CuTe lane next; "
                "keep TMA as a fallback path, not the primary next step."
                if can_integrate
                else "Vector integration is blocked by the listed guard, runtime, or ptxas failures."
            ),
        },
        "blockers": blockers,
        "guard_contract": guard_contract,
        "checks": {
            "alignment_layout": {
                "status": alignment_check["status"],
                "pass": alignment_check["pass"],
                "tile_count": alignment_check.get("tile_count"),
                "tiles_covered": alignment_check.get("tiles_covered"),
                "failures": alignment_check["failures"],
            },
            "runtime_probe": {
                "status": runtime_check["status"],
                "pass": runtime_check["pass"],
                "failures": runtime_check["failures"],
            },
            "ptxas_resource": ptxas_resource_check,
            "guard_contract": guard_contract_check,
        },
        "source_evidence": _source_evidence(effective_runtime, effective_ptxas),
        "validation": {
            "generated_by": "tools/probes/mamba3_wgmma_wave10_copy_integration.py",
            "receipt": RECEIPT_PATH,
            "guide": GUIDE_PATH,
            "guard_header": GUARD_HEADER_PATH,
            "check_command": (
                "python tools/probes/mamba3_wgmma_wave10_copy_integration.py "
                f"--runtime-result {wave9.RUNTIME_RESULT_PATH} "
                f"--ptxas-ingest {wave9.PTXAS_INGEST_PATH} "
                f"--check {RECEIPT_PATH} "
                f"--check-guard-header {GUARD_HEADER_PATH} "
                f"--check-guide {GUIDE_PATH}"
            ),
            "write_command": (
                "python tools/probes/mamba3_wgmma_wave10_copy_integration.py "
                f"--runtime-result {wave9.RUNTIME_RESULT_PATH} "
                f"--ptxas-ingest {wave9.PTXAS_INGEST_PATH} "
                f"--write {RECEIPT_PATH} "
                f"--write-guard-header {GUARD_HEADER_PATH} "
                f"--write-guide {GUIDE_PATH}"
            ),
        },
    }
    _validate_receipt(receipt)
    return receipt


def _validate_receipt(receipt: dict[str, Any]) -> None:
    constants = receipt["guard_contract"]["constants"]
    assert constants["logical_tile_count"] == 12
    assert constants["vectors_per_chunk"] == 6144
    assert constants["dynamic_smem_bytes"] == 98304
    if receipt["decision"]["vector_path_ready"]:
        assert receipt["status"] == "pass_cute_integration_ready_vector_first"
        assert receipt["decision"]["recommendation"] == "integrate_vector_path_next"
        assert not receipt["blockers"]
    else:
        assert receipt["blockers"]


def render_markdown_guide(receipt: dict[str, Any]) -> str:
    evidence = receipt["source_evidence"]
    runtime = evidence["runtime"]
    timing = runtime.get("timing") or {}
    device = runtime.get("device") or {}
    ptxas = evidence["ptxas"].get("metadata") or {}
    decision = receipt["decision"]

    return f"""# Mamba3 Mono WGMMA Copy Path Wave10 CuTe Integration - {DATE}

Status: active
Canonical: none
Date: {DATE}
Scope: Integration-ready contract for the 12-tile `uint4` vector copy path in the CuTe lane.

## Decision

Final recommendation: `{decision["recommendation"]}`.

Vector path status: `{decision["vector_path_ready"]}`.  TMA status:
`{decision["tma_fallback"]}`.

Reason: Wave9 correctness passed byte-for-byte against the scalar CUDA
reference, ptxas reported `{ptxas.get("registers_per_thread")}` registers and
zero spills, and the retained runtime measured `{timing.get("vector_avg_us")}`
us vector copy vs `{timing.get("scalar_avg_us")}` us scalar copy on
`{device.get("name")}`.

## Retained Artifacts

- Receipt: `{RECEIPT_PATH}`
- Guard header consumed by the runtime probe: `{GUARD_HEADER_PATH}`
- Source runtime evidence: `{wave9.RUNTIME_RESULT_PATH}`
- Source ptxas evidence: `{wave9.PTXAS_INGEST_PATH}`

## Guard Conditions

Compile-time guards:

- 64x64 BF16 tiles, `row_bytes=128`, `tile_bytes=8192`
- `uint4` lanes are 16 bytes and cover eight contiguous BF16 values
- no row or tile tail exists for this specialization
- exactly 10 global-source tiles and 2 CTA-local-stage tiles per chunk
- dynamic SMEM launch contract is `98304` bytes

Runtime guards:

- global, CTA-local, destination, and SMEM bases are 16-byte aligned
- row stride is 128 bytes and panel offsets are 16-byte aligned
- block size is a positive warp multiple
- device dynamic SMEM opt-in capacity is at least `98304` bytes
- a barrier follows the SMEM load and another barrier protects SMEM reuse

## Expected Data Layouts

| Tile group | Count | Source | Destination/layout |
| --- | ---: | --- | --- |
| K/Q/K_T/Q_T/state/dPhiO/PsiV | 10 | global | 64x64 BF16 physical rows, 128 bytes/row, 512 `uint4` lanes/tile |
| dstates panels | 2 | CTA-local stage | same 64x64 BF16 physical row contract |
| K_T/Q_T | 2 | global physical-layout/view operands | vector-compatible CuTe/GMMA layout, not per-column BF16 scatter |

## API Sketch

```c++
#include "tools/probes/mamba3_wgmma_wave10_copy_guards.hpp"

template <class GlobalTiles, class LocalStageTiles, class SmemTiles>
CUTE_DEVICE void copy_12tile_uint4_to_smem(
    GlobalTiles const& global_tiles,
    LocalStageTiles const& local_stage_tiles,
    SmemTiles& smem_tiles,
    int chunk_idx,
    int* status);
```

The generated code should call
`mamba3_wave10_copy::runtime_guard_bits(...)`, copy ten global tiles and two
CTA-local tiles as `uint4`, synchronize before WGMMA consumption, then
synchronize again before reusing the 12-tile staging buffer.

## Failure Modes

| Mode | Detection | Action |
| --- | --- | --- |
| misaligned source/destination | guard status bits | block vector launch; use scalar repair or TMA fallback |
| row or panel stride mismatch | generated layout guard | fix layout before enabling `uint4` |
| K_T/Q_T scalar scatter | transpose layout proof/codegen inspection | keep physical-layout view or switch to TMA smoke |
| masked tail emitted | guard contract/codegen inspection | remove tail path from this specialization |
| SMEM opt-in too small | dynamic SMEM guard | skip vector path on that target |
| resource regression | ptxas check | keep TMA fallback if regs spill or exceed budget |
| correctness regression | scalar byte-equality probe | block integration and investigate TMA fallback |

## Validation

```text
{receipt["validation"]["check_command"]}
```

Focused tests:

```text
pytest tests/test_mamba3_wgmma_wave10_copy_integration.py tests/test_mamba3_wgmma_wave9_copy_probe.py
```
"""


def _load_optional(path: pathlib.Path | None) -> dict[str, Any] | None:
    if path is None:
        return None
    return _read_json(path)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--runtime-result", type=pathlib.Path, default=None)
    parser.add_argument("--ptxas-ingest", type=pathlib.Path, default=None)
    parser.add_argument("--write", type=pathlib.Path, default=None)
    parser.add_argument("--check", type=pathlib.Path, default=None)
    parser.add_argument("--write-guard-header", type=pathlib.Path, default=None)
    parser.add_argument("--check-guard-header", type=pathlib.Path, default=None)
    parser.add_argument("--write-guide", type=pathlib.Path, default=None)
    parser.add_argument("--check-guide", type=pathlib.Path, default=None)
    args = parser.parse_args()

    runtime_result = _load_optional(args.runtime_result)
    ptxas_ingest = _load_optional(args.ptxas_ingest)
    receipt = build_receipt(runtime_result=runtime_result, ptxas_ingest=ptxas_ingest)
    rendered_receipt = _canonical(receipt)
    rendered_header = render_guard_header()
    rendered_guide = render_markdown_guide(receipt)

    if args.write_guard_header:
        _write_text(args.write_guard_header, rendered_header)
    if args.check_guard_header:
        if args.check_guard_header.read_text() != rendered_header:
            raise SystemExit(f"{args.check_guard_header} does not match generated guard header")

    if args.write_guide:
        _write_text(args.write_guide, rendered_guide)
    if args.check_guide:
        if args.check_guide.read_text() != rendered_guide:
            raise SystemExit(f"{args.check_guide} does not match generated guide")

    if args.write:
        _write_json(args.write, receipt)
    if args.check:
        if args.check.read_text() != rendered_receipt:
            raise SystemExit(f"{args.check} does not match generated receipt")
        return

    wrote_or_checked = any(
        (
            args.write,
            args.write_guard_header,
            args.check_guard_header,
            args.write_guide,
            args.check_guide,
        )
    )
    if not wrote_or_checked:
        print(rendered_receipt, end="")


if __name__ == "__main__":
    main()
