// Generated by tools/probes/mamba3_wgmma_wave10_copy_integration.py.
// schema: mamba3_wave10_copy_guard_header_v1
#pragma once

#include <stdint.h>

namespace mamba3_wave10_copy {

constexpr int kTileRows = 64;
constexpr int kTileCols = 64;
constexpr int kBf16Bytes = 2;
constexpr int kVectorBytes = 16;
constexpr int kWarpThreads = 32;
constexpr int kLogicalTileCount = 12;
constexpr int kGlobalTileCount = 10;
constexpr int kLocalStageTileCount = 2;
constexpr int kTileElements = kTileRows * kTileCols;
constexpr int kRowBytes = kTileCols * kBf16Bytes;
constexpr int kTileBytes = kTileElements * kBf16Bytes;
constexpr int kVectorsPerRow = kRowBytes / kVectorBytes;
constexpr int kVectorsPerTile = kTileBytes / kVectorBytes;
constexpr int kElementsPerVector = kVectorBytes / kBf16Bytes;
constexpr int kTotalVectors = kLogicalTileCount * kVectorsPerTile;
constexpr int kTotalElements = kLogicalTileCount * kTileElements;
constexpr int kDynamicSmemBytes = kLogicalTileCount * kTileBytes;

constexpr bool kStaticLayoutGuardsPass =
    kTileRows == 64 &&
    kTileCols == 64 &&
    kBf16Bytes == 2 &&
    kVectorBytes == 16 &&
    kRowBytes == 128 &&
    kTileBytes == 8192 &&
    kVectorsPerRow == 8 &&
    kVectorsPerTile == 512 &&
    kElementsPerVector == 8 &&
    kTotalVectors == 6144 &&
    kDynamicSmemBytes == 98304 &&
    (kRowBytes % kVectorBytes) == 0 &&
    (kTileBytes % kVectorBytes) == 0 &&
    kGlobalTileCount + kLocalStageTileCount == kLogicalTileCount;

enum GuardStatusBits : int {
  kGuardStatusOk = 0,
  kGuardMisalignedGlobalSource = 1 << 0,
  kGuardMisalignedLocalStageSource = 1 << 1,
  kGuardMisalignedDestination = 1 << 2,
  kGuardMisalignedSmem = 1 << 3,
  kGuardInvalidBlockThreads = 1 << 4,
};

__host__ __device__ __forceinline__ bool is_aligned_16(const void* ptr) {
  return (reinterpret_cast<uintptr_t>(ptr) & (kVectorBytes - 1)) == 0;
}

__host__ __device__ __forceinline__ bool row_stride_guard(int64_t row_stride_bytes) {
  return row_stride_bytes == kRowBytes &&
      (row_stride_bytes % kVectorBytes) == 0;
}

__host__ __device__ __forceinline__ bool panel_offset_guard(int64_t panel_offset_bytes) {
  return (panel_offset_bytes % kVectorBytes) == 0;
}

__host__ __device__ __forceinline__ bool dynamic_smem_optin_guard(
    int max_dynamic_smem_optin_bytes) {
  return max_dynamic_smem_optin_bytes >= kDynamicSmemBytes;
}

__device__ __forceinline__ int runtime_guard_bits(
    const void* global_src,
    const void* local_stage_src,
    const void* dst,
    const void* smem,
    int block_threads) {
  int bits = kGuardStatusOk;
  if (!is_aligned_16(global_src)) {
    bits |= kGuardMisalignedGlobalSource;
  }
  if (!is_aligned_16(local_stage_src)) {
    bits |= kGuardMisalignedLocalStageSource;
  }
  if (!is_aligned_16(dst)) {
    bits |= kGuardMisalignedDestination;
  }
  if (!is_aligned_16(smem)) {
    bits |= kGuardMisalignedSmem;
  }
  if (block_threads <= 0 || (block_threads % kWarpThreads) != 0) {
    bits |= kGuardInvalidBlockThreads;
  }
  return bits;
}

}  // namespace mamba3_wave10_copy
