"""Reproducer for PR: Eliminate redundant V @ dO^T dot product in SISO backward kernel.

Template: upstream_prs/04_mamba3_siso_bwd_eliminate_redundant_vdot.md
Target:   state-spaces/mamba -> mamba_ssm/ops/triton/mamba3/mamba3_siso_bwd.py

What this script does
----------------------
1.  Loads mamba_ssm.ops.triton.mamba3.mamba3_siso_bwd unmodified (the upstream
    code which runs `tl.dot(v_block, tl.trans(do_block))` three times in the
    inner chunk loop of `mamba3_siso_bwd_kernel_dqkv`).
2.  Replaces that kernel at runtime with a hand-patched version that computes
    `V @ dO^T` once and reuses the masked result for dADT, dK and dQ.
3.  Runs `mamba3_siso_combined` forward + backward with both variants on the
    same RNG state and compares every gradient tensor (Q, K, V, ADT, DT, Trap,
    Q_bias, K_bias, Angles, D, Z).  Exits non-zero on any mismatch above
    `REL_TOL`.
4.  Times the backward call for both variants (cuda events, warmup + N iters)
    and prints the timing delta.

The optimized kernel is generated by AST-editing the bwd module's source, then
exec'd in a clean namespace that mirrors the module's imports.  This keeps the
reproducer fully self-contained - nothing is written to the installed package.
"""
from __future__ import annotations

import argparse
import ast
import importlib
import inspect
import math
import os
import sys
import textwrap
import types
from typing import Optional, Tuple

import torch
import torch.nn.functional as F

# ------------------------------------------------------------------
# Command-line
# ------------------------------------------------------------------
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--batch", type=int, default=1)
parser.add_argument("--seqlen", type=int, default=4096)
parser.add_argument("--nheads", type=int, default=24)
parser.add_argument("--nheads_qk", type=int, default=24)
parser.add_argument("--headdim_qk", type=int, default=64)
parser.add_argument("--headdim_v", type=int, default=128)
parser.add_argument("--chunk_size", type=int, default=64)
parser.add_argument("--dtype", type=str, default="bfloat16",
                    choices=["bfloat16", "float16"])
parser.add_argument("--warmup", type=int, default=5)
parser.add_argument("--iters", type=int, default=25)
parser.add_argument("--rel-tol", type=float, default=2e-3,
                    help="max allowed max-relative-error per gradient")
parser.add_argument("--abs-tol", type=float, default=1e-3)
parser.add_argument("--seed", type=int, default=1234)
parser.add_argument("--no-Z", action="store_true")
parser.add_argument("--no-D", action="store_true")
args = parser.parse_args()

DTYPE_MAP = {"bfloat16": torch.bfloat16, "float16": torch.float16}
DTYPE = DTYPE_MAP[args.dtype]

assert torch.cuda.is_available(), "CUDA required"
device = torch.device("cuda")
print(f"[env] torch={torch.__version__} device={torch.cuda.get_device_name(0)}")

import triton
print(f"[env] triton={triton.__version__}")

import mamba_ssm
print(f"[env] mamba_ssm={mamba_ssm.__version__}")

# ------------------------------------------------------------------
# Load the upstream bwd module and build a patched twin
# ------------------------------------------------------------------
from mamba_ssm.ops.triton.mamba3 import mamba3_siso_bwd as siso_bwd_mod
from mamba_ssm.ops.triton.mamba3 import mamba3_siso_combined as siso_combined_mod
from mamba_ssm.ops.triton.mamba3.mamba3_siso_combined import mamba3_siso_combined

ORIGINAL_KERNEL = siso_bwd_mod.mamba3_siso_bwd_kernel_dqkv

# The patch text below is the same diff described in the PR template.  We
# operate on the *source* of the installed module (not the kernel object) so we
# can preserve autotune decorators and helper imports exactly.
_ORIG_BLOCK = '''        # ============================================================
        # Compute dADT Gradient (Part 1): From Intra-chunk Attention
        # This is register-heavy so we compute it early before spilling
        # ============================================================
        # Gradient contribution from (QK^T ⊙ L) V term
        dAinv = tl.dot(v_block, tl.trans(do_block))  # V @ dO^T
        if RECOMPUTE_MASK:
            dAinv *= tl.math.exp2(tl.minimum(da_cs[None, :] - da_cs[:, None], 0.0))
            dAinv = tl.where(
                tl.arange(0, CHUNK_SIZE)[None, :] > tl.arange(0, CHUNK_SIZE)[:, None],
                dAinv,
                0.0
            )
        else:
            dAinv *= causal_decay_mask
        dAinv *= tl.dot(k_block, tl.trans(q_block))  # Element-wise with K @ Q^T
        dM_rev_vector = tl.sum(dAinv, axis=0) - tl.sum(dAinv, axis=1)  # (CHUNK_SIZE,)

        # ============================================================
        # Compute dK: Key Gradient
        # dK = (V @ dO^T ⊙ mask)^T @ Q + V @ dStates * scale
        # ============================================================
        # Intra-chunk: dP^T @ Q where dP = dO @ V^T ⊙ mask
        dp_t_block = tl.dot(v_block, tl.trans(do_block))  # V @ dO^T: (CHUNK_SIZE, CHUNK_SIZE)
        if RECOMPUTE_MASK:
            dp_t_block *= tl.math.exp2(tl.minimum(da_cs[None, :] - da_cs[:, None], 0.0))
            dp_t_block = tl.where(
                tl.arange(0, CHUNK_SIZE)[None, :] > tl.arange(0, CHUNK_SIZE)[:, None],
                dp_t_block,
                0.0
            )
        else:
            dp_t_block *= causal_decay_mask

        acc_dk = tl.dot(dp_t_block.to(q_block.dtype), q_block)  # (CHUNK_SIZE, HEADDIM_QK)'''

_PATCHED_BLOCK = '''        # ============================================================
        # Compute V @ dO^T Once (shared by dADT, dK, dQ)  -- PR #04 patched
        # ============================================================
        vdot_block = tl.dot(v_block, tl.trans(do_block))  # V @ dO^T: (CHUNK_SIZE, CHUNK_SIZE)

        if RECOMPUTE_MASK:
            vdot_masked = vdot_block * tl.math.exp2(tl.minimum(da_cs[None, :] - da_cs[:, None], 0.0))
            vdot_masked = tl.where(
                tl.arange(0, CHUNK_SIZE)[None, :] > tl.arange(0, CHUNK_SIZE)[:, None],
                vdot_masked,
                0.0
            )
        else:
            vdot_masked = vdot_block * causal_decay_mask

        # ============================================================
        # Compute dADT Gradient (Part 1): From Intra-chunk Attention
        # ============================================================
        dAinv = vdot_masked * tl.dot(k_block, tl.trans(q_block))
        dM_rev_vector = tl.sum(dAinv, axis=0) - tl.sum(dAinv, axis=1)  # (CHUNK_SIZE,)

        # ============================================================
        # Compute dK: Key Gradient
        # dK = (V @ dO^T ⊙ mask)^T @ Q + V @ dStates * scale
        # ============================================================
        acc_dk = tl.dot(vdot_masked.to(q_block.dtype), q_block)  # (CHUNK_SIZE, HEADDIM_QK)'''

_ORIG_DQ = '''        # Intra-chunk: S^T @ K where S = V @ dO^T ⊙ mask
        s_block = tl.dot(v_block, tl.trans(do_block))  # (CHUNK_SIZE, CHUNK_SIZE)
        if RECOMPUTE_MASK:
            s_block *= tl.math.exp2(tl.minimum(da_cs[None, :] - da_cs[:, None], 0.0))
            s_block = tl.where(
                tl.arange(0, CHUNK_SIZE)[None, :] > tl.arange(0, CHUNK_SIZE)[:, None],
                s_block,
                0.0
            )
        else:
            s_block *= causal_decay_mask

        acc_dq = tl.dot(tl.trans(s_block).to(k_block.dtype), k_block)  # (CHUNK_SIZE, HEADDIM_QK)'''

_PATCHED_DQ = '''        # Intra-chunk: S^T @ K where S = V @ dO^T ⊙ mask  -- reuses vdot_masked from PR #04
        acc_dq = tl.dot(tl.trans(vdot_masked).to(k_block.dtype), k_block)  # (CHUNK_SIZE, HEADDIM_QK)'''


def build_patched_kernel():
    """Return a fresh Triton JIT kernel object with the vdot fusion applied.

    Triton's JIT re-parses kernel source via `inspect.getsource` at compile
    time, so the patched source must live in a real file on disk.  We copy the
    upstream module text to a temp file under a unique package name, apply the
    two substitutions, then import it and hand back its kernel.
    """
    import pathlib, tempfile, importlib.util

    src = inspect.getsource(siso_bwd_mod)
    if _ORIG_BLOCK not in src:
        raise RuntimeError(
            "Could not locate the original dADT/dK block in mamba3_siso_bwd.py -- "
            "the upstream source has drifted; update _ORIG_BLOCK in reproducer.py."
        )
    if _ORIG_DQ not in src:
        raise RuntimeError(
            "Could not locate the original dQ block in mamba3_siso_bwd.py -- "
            "the upstream source has drifted; update _ORIG_DQ in reproducer.py."
        )
    patched_src = src.replace(_ORIG_BLOCK, _PATCHED_BLOCK).replace(_ORIG_DQ, _PATCHED_DQ)

    assert patched_src.count("tl.dot(v_block, tl.trans(do_block))") == 1, (
        "Patched source should have exactly one V@dO^T dot; got "
        f"{patched_src.count('tl.dot(v_block, tl.trans(do_block))')}"
    )

    # Write under a unique filename so Triton's cache doesn't alias the orig
    tmpdir = pathlib.Path(tempfile.mkdtemp(prefix="pr04_vdot_"))
    patched_path = tmpdir / "mamba3_siso_bwd_patched.py"
    patched_path.write_text(patched_src)

    spec = importlib.util.spec_from_file_location(
        "mamba3_siso_bwd_patched_pr04", str(patched_path)
    )
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return mod.mamba3_siso_bwd_kernel_dqkv


PATCHED_KERNEL = build_patched_kernel()
print("[build] patched kernel compiled OK "
      f"(orig id={id(ORIGINAL_KERNEL):#x}, patched id={id(PATCHED_KERNEL):#x})")


def install_kernel(kernel):
    """Swap the kernel referenced by compute_dqkv inside the bwd module."""
    siso_bwd_mod.mamba3_siso_bwd_kernel_dqkv = kernel


# ------------------------------------------------------------------
# Input generation (mirrors state-spaces/mamba tests/ops/triton/test_mamba3_siso.py)
# ------------------------------------------------------------------
def make_inputs(requires_grad: bool):
    torch.manual_seed(args.seed)
    torch.cuda.manual_seed_all(args.seed)

    B, S = args.batch, args.seqlen
    NH, NHQK = args.nheads, args.nheads_qk
    DQK, DV = args.headdim_qk, args.headdim_v

    Q = F.rms_norm(torch.randn(B, S, NHQK, DQK, device=device, dtype=DTYPE),
                   normalized_shape=(DQK,)).clone()
    K = F.rms_norm(torch.randn(B, S, NHQK, DQK, device=device, dtype=DTYPE),
                   normalized_shape=(DQK,)).clone()
    V = torch.randn(B, S, NH, DV, device=device, dtype=DTYPE)

    dt_max, dt_min = 0.1, 0.001
    a_init = -torch.empty(B, NH, S, device=device, dtype=torch.float32).uniform_(1.0, 16.0)
    dt = torch.exp(
        torch.rand(B, NH, S, device=device, dtype=torch.float32)
        * (math.log(dt_max) - math.log(dt_min)) + math.log(dt_min)
    )
    ADT = (a_init * dt).contiguous()
    DT = dt.contiguous()
    Trap = torch.empty(B, NH, S, device=device, dtype=DTYPE).uniform_(0.0, 1.0).clone()
    Q_bias = torch.randn(NH, DQK, device=device, dtype=DTYPE)
    K_bias = torch.randn(NH, DQK, device=device, dtype=DTYPE)

    headdim_angles = DQK // 4
    Angles = torch.randn(B, S, NH, headdim_angles, device=device, dtype=torch.float32)

    D = torch.ones((NH,), device=device, dtype=torch.float32) if not args.no_D else None
    Z = torch.randn(B, S, NH, DV, device=device, dtype=DTYPE) if not args.no_Z else None

    tensors = dict(Q=Q, K=K, V=V, ADT=ADT, DT=DT, Trap=Trap,
                   Q_bias=Q_bias, K_bias=K_bias, Angles=Angles,
                   D=D, Z=Z)
    if requires_grad:
        for name, t in tensors.items():
            if t is not None and t.is_floating_point():
                t.requires_grad_(True)

    # Fixed grad_out shared by both variants
    torch.manual_seed(args.seed + 1)
    grad_out = torch.randn(B, S, NH, DV, device=device, dtype=DTYPE)
    return tensors, grad_out


def forward_backward(tensors, grad_out):
    out = mamba3_siso_combined(
        tensors["Q"], tensors["K"], tensors["V"],
        tensors["ADT"], tensors["DT"], tensors["Trap"],
        tensors["Q_bias"], tensors["K_bias"], tensors["Angles"],
        D=tensors["D"], Z=tensors["Z"],
        Input_States=None,
        chunk_size=args.chunk_size,
        return_final_states=False,
        cu_seqlens=None,
    )
    # Zero existing grads
    for t in tensors.values():
        if isinstance(t, torch.Tensor) and t.grad is not None:
            t.grad = None
    out.backward(grad_out)
    grads = {}
    for name, t in tensors.items():
        if isinstance(t, torch.Tensor) and t.requires_grad:
            grads[name] = t.grad.detach().clone()
    return out.detach().clone(), grads


# ------------------------------------------------------------------
# Correctness: bitwise-identical expected by the PR template, but we allow
# rel-tol to leave room for reorderings.
# ------------------------------------------------------------------
print("\n=== Correctness ===")
print(f"config: B={args.batch} S={args.seqlen} NH={args.nheads} NHQK={args.nheads_qk} "
      f"DQK={args.headdim_qk} DV={args.headdim_v} chunk={args.chunk_size} dtype={args.dtype}")

install_kernel(ORIGINAL_KERNEL)
tensors_orig, grad_out = make_inputs(requires_grad=True)
out_orig, grads_orig = forward_backward(tensors_orig, grad_out)
torch.cuda.synchronize()

install_kernel(PATCHED_KERNEL)
tensors_new, grad_out2 = make_inputs(requires_grad=True)
# same seed => identical inputs, but assert it
assert torch.equal(grad_out, grad_out2)
out_new, grads_new = forward_backward(tensors_new, grad_out2)
torch.cuda.synchronize()

# Forward should be identical (this PR only touches bwd)
out_max_abs = (out_orig.float() - out_new.float()).abs().max().item()
print(f"fwd max |orig - patched| = {out_max_abs:.3e}")
if out_max_abs > 0:
    print(f"WARNING: forward differs by {out_max_abs:.3e}; PR only edits bwd, expected 0")

fail = False
for name in sorted(grads_orig):
    a = grads_orig[name].float()
    b = grads_new[name].float()
    diff = (a - b).abs()
    denom = a.abs().clamp_min(1e-6)
    rel = (diff / denom).max().item()
    absmax = diff.max().item()
    status = "OK" if (rel < args.rel_tol and absmax < args.abs_tol) else "FAIL"
    if status == "FAIL":
        fail = True
    print(f"  grad[{name:8s}]  abs_max={absmax:.3e}  rel_max={rel:.3e}  [{status}]")

if fail:
    print("CORRECTNESS FAIL - patched kernel gradients diverge beyond tolerance")
    sys.exit(1)
print("CORRECTNESS OK")


# ------------------------------------------------------------------
# Timing
# ------------------------------------------------------------------
print("\n=== Timing (bwd only, autotune warmed) ===")

def bench(kernel_obj, label):
    install_kernel(kernel_obj)
    # Fresh input set each time so saved_tensors are aligned with the swap
    tensors, grad_out = make_inputs(requires_grad=True)

    # Warmup (covers autotune)
    for _ in range(args.warmup):
        for t in tensors.values():
            if isinstance(t, torch.Tensor) and t.grad is not None:
                t.grad = None
        out = mamba3_siso_combined(
            tensors["Q"], tensors["K"], tensors["V"],
            tensors["ADT"], tensors["DT"], tensors["Trap"],
            tensors["Q_bias"], tensors["K_bias"], tensors["Angles"],
            D=tensors["D"], Z=tensors["Z"], Input_States=None,
            chunk_size=args.chunk_size, return_final_states=False, cu_seqlens=None,
        )
        out.backward(grad_out, retain_graph=False)
    torch.cuda.synchronize()

    # Timed loop - we re-run full fwd+bwd each iter because saved_tensors are
    # consumed on backward; then subtract an fwd-only baseline measured the
    # same way.
    start = [torch.cuda.Event(enable_timing=True) for _ in range(args.iters)]
    end = [torch.cuda.Event(enable_timing=True) for _ in range(args.iters)]
    fb_times = []
    for i in range(args.iters):
        for t in tensors.values():
            if isinstance(t, torch.Tensor) and t.grad is not None:
                t.grad = None
        start[i].record()
        out = mamba3_siso_combined(
            tensors["Q"], tensors["K"], tensors["V"],
            tensors["ADT"], tensors["DT"], tensors["Trap"],
            tensors["Q_bias"], tensors["K_bias"], tensors["Angles"],
            D=tensors["D"], Z=tensors["Z"], Input_States=None,
            chunk_size=args.chunk_size, return_final_states=False, cu_seqlens=None,
        )
        out.backward(grad_out, retain_graph=False)
        end[i].record()
    torch.cuda.synchronize()
    fb_times = [s.elapsed_time(e) for s, e in zip(start, end)]

    # Forward-only baseline with same inputs / no grad (for bwd isolation)
    tensors_nograd, grad_out_ng = make_inputs(requires_grad=False)
    fwd_times = []
    for _ in range(args.warmup):
        _ = mamba3_siso_combined(
            tensors_nograd["Q"], tensors_nograd["K"], tensors_nograd["V"],
            tensors_nograd["ADT"], tensors_nograd["DT"], tensors_nograd["Trap"],
            tensors_nograd["Q_bias"], tensors_nograd["K_bias"], tensors_nograd["Angles"],
            D=tensors_nograd["D"], Z=tensors_nograd["Z"], Input_States=None,
            chunk_size=args.chunk_size, return_final_states=False, cu_seqlens=None,
        )
    torch.cuda.synchronize()
    for i in range(args.iters):
        s = torch.cuda.Event(enable_timing=True); e = torch.cuda.Event(enable_timing=True)
        s.record()
        _ = mamba3_siso_combined(
            tensors_nograd["Q"], tensors_nograd["K"], tensors_nograd["V"],
            tensors_nograd["ADT"], tensors_nograd["DT"], tensors_nograd["Trap"],
            tensors_nograd["Q_bias"], tensors_nograd["K_bias"], tensors_nograd["Angles"],
            D=tensors_nograd["D"], Z=tensors_nograd["Z"], Input_States=None,
            chunk_size=args.chunk_size, return_final_states=False, cu_seqlens=None,
        )
        e.record()
        torch.cuda.synchronize()
        fwd_times.append(s.elapsed_time(e))

    fb_times.sort(); fwd_times.sort()
    # use medians to suppress autotune-retuning spikes
    fb_med = fb_times[len(fb_times)//2]
    fwd_med = fwd_times[len(fwd_times)//2]
    bwd_med = fb_med - fwd_med
    print(f"[{label:8s}] fwd+bwd med = {fb_med:7.3f} ms | fwd med = {fwd_med:7.3f} ms | "
          f"bwd med = {bwd_med:7.3f} ms")
    return bwd_med


bwd_orig = bench(ORIGINAL_KERNEL, "orig")
bwd_patched = bench(PATCHED_KERNEL, "patched")

delta = bwd_orig - bwd_patched
speedup_pct = (delta / bwd_orig) * 100.0 if bwd_orig > 0 else 0.0
print(f"\nbwd delta = {delta:+.3f} ms  ({speedup_pct:+.2f}%)")
print("(template notes Triton CSE already fuses these dots, so near-zero "
      "delta on recent Triton is expected; patch value is in code clarity "
      "and robustness to older Triton / other arches.)")

sys.exit(0)
